aws_region = "eu-central-1"
aws_profile = "default"

name = "test"
stage = "dev"
project = "test"
default_domain = "example.com"
alt_domain = "*.example.com"
proj-tag = "test"
cors-origin-1 = "https://dev.carvago.utdigit.com" 